package main

import (
	"bufio"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"strings"
	"unicode"
)

var templateLine string = `    %s = "%s",`

var ServiceApiMapTemplate string = `--Generated By go-parse-proto Do not Edit
local config = {
%s
}
return config`

var MatchMapTemplate string = `--Generated By go-parse-proto Do not Edit
local config = {
	Ping = "Pong",
%s
}
return config`

func main() {
	var NameList = []string{}
	data,err := ioutil.ReadFile("./proto/hamster.proto")
	if err == nil {
		sr := strings.NewReader(string(data))
		reader := bufio.NewReader(sr)
		for {
			line,_,err := reader.ReadLine()
			if err == io.EOF {
				break
			}
			//fmt.Println(string(line),ispre)
			strLine := string(line)
			if strings.HasPrefix(strLine,"message"){
				splitStr := strings.Trim(strLine,"message ")
				protoName := strings.TrimRight(splitStr," {}")
				NameList = append(NameList,protoName)
			}
		}
	}
	//必须存在request
	//取掉request去找response
	var name string
	for _, s := range (NameList){
		if strings.Contains(s,"Request") || (strings.Contains(s,"Response") || s == "Ping" || s == "Pong") {
			fmt.Println("s = " + s)
			ret:= Parse(s)
			format := fmt.Sprintf(templateLine, ret, s)
			name = name + format + "\n"
		}
	}
	fmt.Println("ServiceApiMap = \n" + name)
	outStr := fmt.Sprintf(ServiceApiMapTemplate,name)
	dstFile,err :=os.Create("./ServiceApiMap.lua")
	dstFile.WriteString(outStr)
	dstFile.Close()

	var math string
	for _, s := range (NameList){
		if s == "Request" || s == "Response" || s == "Ping" || s == "Pong" {
			continue
		}
		if strings.Contains(s,"Request") {
			replace := strings.ReplaceAll(s,"Request","Response")
			var Contains bool = false
			for _, ss := range (NameList) {
				if ss == replace {
					Contains = true
					break
				}
			}
			if Contains {
				format := fmt.Sprintf(templateLine, s, replace)
				math = math + format + "\n"
			}else{
				fmt.Println("Match not find." + s)
			}
		}
	}

	fmt.Println("MatchMap = \n" + math)
	MatchMapOutStr := fmt.Sprintf(MatchMapTemplate,math)
	MatchMapDstFile,err :=os.Create("./MatchMap.lua")
	MatchMapDstFile.WriteString(MatchMapOutStr)
	MatchMapDstFile.Close()

	fmt.Println("Parse Successful !")
}

func Parse(str string) string {
	// deep copy
	//b := make([]byte, len(str))
	//copy(b, str)
	//newstr := string(b)

	forM := []rune(str)
	ret := []rune{}

	for i := 0; i < (len(forM) - 1); i++ {
		if i!=0 && unicode.IsUpper(forM[i]) && unicode.IsLower(forM[i + 1]) {
			ret = append(ret,rune('_'))
		}

		ret = append(ret,unicode.ToUpper(forM[i]))
	}
	ret = append(ret,unicode.ToUpper(forM[len(forM) - 1]))
	return string(ret)
}
