--Generated By go-parse-proto Do not Edit
local config = {
	Ping = "Pong",
    CollectingStaffsRequest = "CollectingStaffsResponse",
    DebugAddEmailRequest = "DebugAddEmailResponse",
    DebugLoginRequest = "DebugLoginResponse",
    DebugRegisterRequest = "DebugRegisterResponse",
    EmailRequest = "EmailResponse",
    EmployeesRequest = "EmployeesResponse",
    FireEmployeeRequest = "FireEmployeeResponse",
    FoodsRequest = "FoodsResponse",
    ItemsRequest = "ItemsResponse",
    MakeFoodsRequest = "MakeFoodsResponse",
    PlayerRequest = "PlayerResponse",
    RandomListRequest = "RandomListResponse",
    RandomTaskRequest = "RandomTaskResponse",
    RecipeRequest = "RecipeResponse",
    RecruitEmployeeRequest = "RecruitEmployeeResponse",
    RegionsRequest = "RegionsResponse",
    ReqCollectingRequest = "ReqCollectingResponse",
    ReqCollectingStopRequest = "ReqCollectingStopResponse",
    ReqReapCollectingRequest = "ReqReapCollectingResponse",
    SDKGuestBindRequest = "SDKGuestBindResponse",

}
return config